INSERT INTO %db_prefix%modules (module_name,module_display_name,module_description,module_status) VALUES ('stock', 'Medicine Store',"Manage Medicine Stock, Purchase and Sell", '1');
CREATE TABLE IF NOT EXISTS %db_prefix%item (item_id INT(11) NOT NULL AUTO_INCREMENT,item_name VARCHAR( 100 ) NOT NULL,desired_stock INT(11),PRIMARY KEY ( item_id ));
ALTER TABLE %db_prefix%item ADD mrp float(11,2) NOT NULL;
CREATE TABLE IF NOT EXISTS %db_prefix%supplier ( supplier_id INT(11) NOT NULL AUTO_INCREMENT , supplier_name VARCHAR( 100 ) NOT NULL , contact_number VARCHAR(100) , PRIMARY KEY ( supplier_id ) );
CREATE TABLE IF NOT EXISTS %db_prefix%purchase ( purchase_id INT(11) NOT NULL AUTO_INCREMENT , purchase_date DATE DEFAULT NULL , item_id INT(11) NOT NULL , quantity INT(11) NOT NULL , supplier_id INT(11) NOT NULL , cost_price DECIMAL(10,0) DEFAULT NULL , remain_quantity INT(11) NOT NULL , bill_no VARCHAR(255) NOT NULL , mrp FLOAT(11,2) NOT NULL , PRIMARY KEY (purchase_id) );
ALTER TABLE %db_prefix%purchase DROP mrp;
CREATE TABLE IF NOT EXISTS %db_prefix%sell ( sell_id INT(11) NOT NULL AUTO_INCREMENT , sell_date DATE NOT NULL , patient_id INT(11) NOT NULL , visit_id INT(11) NOT NULL , sell_amount DECIMAL(10,0) , PRIMARY KEY ( sell_id ) );
CREATE TABLE IF NOT EXISTS %db_prefix%sell_detail ( sell_detail_id INT(11) NOT NULL AUTO_INCREMENT , sell_id INT(11) NOT NULL , item_id INT(11) NOT NULL , quantity INT(11) NOT NULL , sell_price DECIMAL(10,0) , sell_amount DECIMAL(10,0) , PRIMARY KEY ( sell_detail_id ) );
CREATE OR REPLACE VIEW %db_prefix%view_purchase AS SELECT purchase_id,purchase_date,item_name,quantity,supplier_name,cost_price,a.item_id,a.supplier_id,a.remain_quantity,a.bill_no FROM %db_prefix%purchase AS a, %db_prefix%item AS b, %db_prefix%supplier AS c WHERE a.item_id = b.item_id AND a.supplier_id = c.supplier_id;
CREATE OR REPLACE VIEW %db_prefix%view_purchase_total AS SELECT purchase_date,bill_no,SUM(quantity*cost_price) AS total FROM %db_prefix%purchase GROUP BY bill_no;
CREATE OR REPLACE VIEW %db_prefix%view_stock AS SELECT a.item_id,a.item_name,a.desired_stock,(SELECT SUM(b.quantity) FROM %db_prefix%purchase b where a.item_id = b.item_id) purchase_quantity,(SELECT AVG(b.cost_price) FROM %db_prefix%purchase b where a.item_id = b.item_id) avg_purchase_price,(SELECT SUM(c.quantity) FROM %db_prefix%sell_detail c WHERE a.item_id = c.item_id) sell_quantity,(SELECT AVG(c.sell_price) FROM %db_prefix%sell_detail c WHERE a.item_id = c.item_id) avg_sell_price FROM %db_prefix%item a 
CREATE OR REPLACE VIEW %db_prefix%view_available_stock AS SELECT item.item_id,item.item_name,item.desired_stock,item.mrp,IFNULL((SELECT SUM(purchase.quantity) FROM %db_prefix%purchase AS purchase WHERE  item.item_id = purchase.item_id) ,0) - IFNULL((SELECT SUM(sell_detail.quantity) FROM %db_prefix%sell_detail AS sell_detail WHERE  item.item_id = sell_detail.item_id) ,0) available_quantity FROM %db_prefix%item AS item
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock', '', 460,'stock', 'fa-medkit', 'Stock','stock');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_item', 'stock', 100, 'stock/item', '', 'Items','stock');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_supplier', 'stock', 200, 'stock/supplier', '', 'Suppliers','stock');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_purchase', 'stock', 300, 'stock/purchase', '', 'Purchase','stock');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_sell', 'stock', 400, 'stock/sell', '', 'Sell','stock');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_all_sell', 'stock', 450, 'stock/all_sell', '', 'All Sell','stock');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_stock_report', 'stock', 500, 'stock/stock_report', '', 'Stock Report','stock');
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_purchase_report', 'stock', 600, 'stock/purchase_report', '', 'Purchase Report','stock');
INSERT INTO %db_prefix%receipt_template (template,is_default,template_name,type) VALUES ('Test', '1', 'Main', 'sell');
UPDATE %db_prefix%modules SET module_version = '0.0.3' WHERE module_name = 'stock';
-- 0.0.4
UPDATE %db_prefix%receipt_template SET is_default = 0 WHERE type = 'sell';
INSERT INTO %db_prefix%receipt_template (template, is_default, template_name, type) VALUES ('<h1 style="text-align:center;">[clinic_name]</h1><h2 style="text-align:center;">[tag_line]</h2><p style="text-align:center;">[clinic_address]</p><span class="contact"><p style="text-align: center;"><b style="line-height: 1.42857143;">Landline : </b><span style="line-height: 1.42857143;">[landline]</span>  <b style="line-height: 1.42857143;">Mobile : </b><span style="line-height: 1.42857143;">[mobile]</span>  <b style="line-height: 1.42857143;">Email : </b><span style="text-align: center;"> [email]</span></p></span><hr id="null"><h3 style="text-align: center;"><u style="text-align: center;">RECEIPT</u></h3><span style="text-align: left;"><b>Date : </b>[bill_date]</span><span style="float: right;"><b>Receipt Number :</b> [bill_id]</span><p style="text-align: left;"><b style="text-align: left;">Patient Name: </b><span style="text-align: left;">[patient_name]<br></span></p><hr id="null" style="text-align: left;">Received fees for Professional services and other charges of our:<p><br></p><table style="width: 100%;margin-top: 25px;margin-bottom: 25px;border-collapse: collapse;border:1px solid black;"><thead><tr><td style="width: 400px;text-align: left;padding:5px;border:1px solid black;"><b style="width: 400px;text-align: left;">Item</b></td><td style="padding:5px;border:1px solid black;"><b>Quantity</b></td><td style="width: 100px;text-align:right;padding:5px;border:1px solid black;"><b>M.R.P.</b></td><td style="width: 100px;text-align:right;padding:5px;border:1px solid black;"><b>Amount</b></td></tr></thead><tbody>[col:item_name|quantity|sell_price|sell_amount]<tr><td colspan="3" style="padding:5px;border:1px solid black;">Total</td><td style="text-align:right;padding:5px;border:1px solid black;"><b>[total]</b></td></tr></tbody></table>Received with Thanks,<p>For [clinic_name]</p><p><br></p><p><br></p><p>Signature</p><hr id="null">', 1, 'Main', 'sell');
UPDATE %db_prefix%modules SET module_version = '0.0.4' WHERE module_name = 'stock';
-- 0.0.5
UPDATE %db_prefix%modules SET module_version = '0.0.5' WHERE module_name = 'stock';
-- 0.0.6
CREATE OR REPLACE VIEW %db_prefix%view_available_stock AS SELECT item.item_id,item.item_name,item.desired_stock,item.mrp,IFNULL((SELECT SUM(purchase.quantity) FROM %db_prefix%purchase AS purchase WHERE  item.item_id = purchase.item_id) ,0) - IFNULL((SELECT SUM(sell_detail.quantity) FROM %db_prefix%sell_detail AS sell_detail WHERE  item.item_id = sell_detail.item_id) ,0) - IFNULL((SELECT SUM(bill_detail.quantity) FROM %db_prefix%bill_detail AS bill_detail WHERE  item.item_id = bill_detail.item_id) ,0) available_quantity FROM %db_prefix%item AS item
UPDATE %db_prefix%modules SET module_version = '0.0.6' WHERE module_name = 'stock';
-- 0.0.7
ALTER TABLE %db_prefix%sell ADD sell_no INT( 5 ) NOT NULL AFTER sell_id;
ALTER TABLE %db_prefix%sell ADD UNIQUE (sell_no);
UPDATE %db_prefix%sell SET sell_no = sell_id;
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ( 'stock_report', 'stock', 500, '#', NULL, 'Reports', 'stock');
UPDATE %db_prefix%navigation_menu SET parent_name = 'stock_report' WHERE menu_name = 'stock_stock_report';
UPDATE %db_prefix%navigation_menu SET parent_name = 'stock_report' WHERE menu_name = 'stock_purchase_report';
CREATE OR REPLACE VIEW %db_prefix%view_sell_report AS SELECT sell.sell_no,sell.sell_id,sell.sell_date,item.item_id,item.item_name,sell_detail.quantity,sell_detail.sell_price,sell_detail.sell_amount FROM %db_prefix%sell AS sell INNER JOIN %db_prefix%sell_detail AS sell_detail ON sell_detail.sell_id = sell.sell_id INNER JOIN %db_prefix%item AS item ON sell_detail.item_id = item.item_id;  
INSERT INTO %db_prefix%navigation_menu (menu_name,parent_name,menu_order,menu_url,menu_icon,menu_text,required_module) VALUES ('stock_sell_report', 'stock_report', 700, 'stock/sell_report', '', 'All Sell Report','stock');
UPDATE %db_prefix%modules SET module_version = '0.0.7' WHERE module_name = 'stock';


